AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  environment:
    Type: String
  product:
    Type: String
  service:
    Type: String
  databaseName:
    Description: Redshift cluster database name
    Type: String
    AllowedPattern: "([a-z]|[0-9])+"
    Default: dev
  nodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: ra3.xlplus
  masterUserName:
    Description: The user name that is associated with the master user account for
      the cluster that is being created
    Type: String
    Default: awsuser
  clusterType:
    Description: The type of cluster
    Type: String
    Default: single-node
    AllowedValues:
    - single-node
    - multi-node
  kmsKeyId: 
    Type: String
    Default: 855e8801-2f90-42b0-8cc5-3411553778b9
Resources:
  RedshiftClusterSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Cluster subnet group
      SubnetIds: 
        - subnet-0d66b46bd82cb491c 
      Tags:
      - Key: "Name"
        Value: !Sub ${environment}-${product}-${service}-subnetgroup	
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Cluster parameter group
      ParameterGroupFamily: redshift-1.0
      ParameterGroupName: !Sub ${environment}-${product}-${service}-parametergroup
      Parameters:
      - ParameterName: enable_case_sensitive_identifier
        ParameterValue: true

  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: !Sub ${environment}-${product}-${service}
      ClusterType: !Ref clusterType
      DBName: !Ref databaseName
      MasterUsername: !Ref masterUserName
      NodeType: !Ref nodeType
      ClusterParameterGroupName: !Ref RedshiftClusterParameterGroup
      Encrypted: true
      ManageMasterPassword: true
      MasterPasswordSecretKmsKeyId: !Ref kmsKeyId
      KmsKeyId: !Ref kmsKeyId
      VpcSecurityGroupIds: 
        - sg-0517996d367c3f323
      ClusterSubnetGroupName: !Ref RedshiftClusterSubnetGroup
Outputs:
  ClusterEndpoint:
    Description: Cluster endpoint
    Value: !Sub "${RedshiftCluster.Endpoint.Address}:${RedshiftCluster.Endpoint.Port}"
  ClusterName:
    Description: Name of cluster
    Value: !Ref RedshiftCluster
  ParameterGroupName:
    Description: Name of parameter group
    Value: !Ref RedshiftClusterParameterGroup
  RedshiftClusterSubnetGroupName:
    Description: Name of cluster subnet group
    Value: !Ref RedshiftClusterSubnetGroup