AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  environment:
    Type: String
    Default: stage
  product:
    Type: String
    Default: extv
  service:
    Type: String
    Default: redshift
Resources:
  zeroEtlIntegration:
    Type: Custom::ZeroETL
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${environment}-${product}-zeroEtl-lambda'
      TargetIdentifier: redshiftCluster-identifier
      TargetArn: redshiftCluster-ClusterNamespaceArn
      Integrations:
        - SourceIdentifier: !Sub '${environment}-${product}-aurora-identifier'
          SourceArn:  !Sub '${environment}-${product}-aurora-arn'
          IntegrationName: aurora-redshift-integration
